# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa80571b6b82d02b8a2a2a49d8d81e07064e58940f225187be7b6775b7b2583f23aed611ebf3bc9032c7005b2d8c6adbe9c2f81e919a182fc4caa51abcf31e46

test:
  secret_key_base: d9f569fd6ec784b365393f5355486e6671a83b69682047fcf7b48bf90d1b7d78715e2059c34eda1e9ac606d90df343045c335f5e22844547518f2ffcd71a5023

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
